services:
  - type: web
    name: saas-metrics-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: PORT
        value: 8080
      - key: SNOWFLAKE_ACCOUNT
        sync: false
      - key: SNOWFLAKE_USER
        sync: false
      - key: SNOWFLAKE_ROLE
        sync: false
      - key: SNOWFLAKE_WAREHOUSE
        sync: false
      - key: SNOWFLAKE_DATABASE
        sync: false
      - key: SNOWFLAKE_SCHEMA
        sync: false
      - key: SNOWFLAKE_PRIVATE_KEY_PATH
        sync: false
